services:

  table-tennis-backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    command: uv run uvicorn backend.api:app --host 0.0.0.0 --port 8000 --reload
    container_name: table-tennis-backend

  table-tennis-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "42000:4200"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    env_file:
      - .env
    command: sh /app/docker-entrypoint.sh
    depends_on:
      - table-tennis-backend
    container_name: table-tennis-frontend

volumes:
  frontend_node_modules:
